# Makefile for this project
# The Drush Make API version. This should always be 2.
api: 2
# The version of Drupal of this profile. Leave as '7.x' here and define the the exact version in projects below
core: 7.x

defaults:
  projects:
    subdir: "contrib"

projects:
  drupal:
    type: "core"
    version: "7.34"
  ctools:
    subdir: contrib
  views:
    subdir: contrib
  date:
    subdir: contrib
  entity:
    subdir: contrib
  entityreference:
    subdir: contrib
  jquery_update:
    subdir: contrib

#  features:
#    subdir: contrib
#
#  ftools:
#    subdir: contrib
#
  wysiwyg:
    subdir: contrib
  jquery_update:
    subdir: contrib

  libraries:
    subdir: contrib
#
  link:
    subdir: contrib
#
  pathauto:
    subdir: contrib
#
#  strongarm:
#    subdir: contrib
#
#  taxonomy_access_fix:
#    subdir: contrib
#
  token:
    subdir: contrib
#
#  uuid:
#    subdir: contrib
#
  variable:
    subdir: contrib
#
#  devel:
#    subdir: contrib
#
#  EdW modules
#  edw_extras:
#    subdir: edw
#    type: module
#    location: http://fserver.eaudeweb.ro/fserver
